export const SEPARATION_LINE_TYPE = 'separation line';
export type SEPARATION_LINE_TYPE = typeof SEPARATION_LINE_TYPE;

export const SEPARATION_LINE_COMPONENT = 'hr';
export type SEPARATION_LINE_COMPONENT = typeof SEPARATION_LINE_COMPONENT;
