export const SEPARATION_LINE_TYPE = 'separation line';
export type SEPARATION_LINE_TYPE = typeof SEPARATION_LINE_TYPE;

export const SEPARATION_LINE_COMPONENT = 'hr';
export type SEPARATION_LINE_COMPONENT = typeof SEPARATION_LINE_COMPONENT;

export const SEPARATION_LINE_COMMAND_ADD = 'Command[Separation Line] Add';
export type SEPARATION_LINE_COMMAND_ADD = typeof SEPARATION_LINE_COMMAND_ADD;
